#
# This file configures the NewRelic Agent.  
#

# here are the settings that are common to all environments
common: &default_settings
  # the enabled setting is used to turn on the NewRelic Agent.
  enabled: false

  # The newrelic agent generates its own log file to keep its logging information
  # separate from that of your application.  Specify its log level here.
  log_level: info
  
  # specify the host and port of the server that the NewRelic Agent communicates with
  host: www.newrelic.com
  port: 80
  
development:
  <<: *default_settings

test:
  <<: *default_settings
  
production:
  <<: *default_settings
  enabled: true

